# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-02 22:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=12)),
                ('food', models.CharField(max_length=12)),
            ],
        ),
        migrations.DeleteModel(
            name='Greeting',
        ),
    ]
